version: '3.5'
services:
  web:
    build:
      context: ./
      target: dev
    command: npm run dev
    ports:
      - "3000:3000"
  test:
    build:
      context: ./
      target: test
    command: npx cypress run  
